name: study_space
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0
  flutter_svg: ^0.22.0
  flutter_switch: ^0.3.1
  usb_serial: ^0.2.4
  mqtt_client: ^9.2.0
  provider: ^5.0.0
  firebase_core: ^1.1.0
  firebase_auth: ^1.1.3
  google_sign_in: ^5.0.2
  http: ^0.13.3
  intl: ^0.17.0
  charts_flutter: ^0.10.0
  syncfusion_flutter_calendar: ^19.1.67
  flutter_local_notifications: ^6.0.0
  sliding_card: ^0.1.2
  awesome_dialog: ^2.1.0
  syncfusion_flutter_gauges: ^19.1.66
  fab_circular_menu: ^1.0.2
  circular_menu: ^1.2.2
  web_socket_channel: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/images/
    - assets/json/grade1/
    - assets/img/char/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/Aeonik-Regular.otf
        - asset: assets/fonts/Aeonik-RegularItalic.otf
          style: italic
        - asset: assets/fonts/Aeonik-Bold.otf
          weight: 700
    - family: Gotham
      fonts:
        - asset: assets/fonts/GothamMedium.ttf
        - asset: assets/fonts/GothamMediumItalic.ttf
          style: italic
        - asset: assets/fonts/GothamBold.ttf
          weight: 700
    - family: Opensans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: ProximaNova
      fonts:
#        - asset: assets/fonts/Proxima-Nova-Soft-Regular.ttf
        - asset: assets/fonts/Proxima-Nova-Soft-Semibold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
